name: CDH-CICD Azure SQL
run-name: CDH-CICD Azure SQL

on:
  push:
#   paths:
#       - 'SqlProject/**'
#       - '**/cicd_pipeline_sql.yml'
    branches:
    - dev
  workflow_dispatch:
  
env:
  projectName: Azure-sql-db-cicd
  buildLocation: ${{ github.workspace }}\build

################## Start: Build ####################### 
 
jobs:
  Build:
    name: Build Stage
    runs-on: Windows-2019
    steps:
    - name: Create a build directory
      run: mkdir ${{github.workspace}}/build
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build solution ${{ github.workspace }}/${{ env.projectName }}/${{ env.projectName }}.sqlproj
      run: msbuild '${{ github.workspace }}/${{env.projectName}}/${{env.projectName }}.sqlproj ' /t:build /p:CmdLineInMemoryStorage=True /p:OutputPath = ${{env.buildLocation }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.projectName }}
        path: ${{ env.buildLocation }}
        
################## End: Build #######################


################## Start: Deploy to ACC #####################

  DeployAcc:
    needs: [Build]
    name: ACC Deploy
    runs-on: ubuntu-latest
    environment:
      name: ACC
    steps:
      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.projectName }}
          path: ${{ env.projectName }}

######Start Login with secrete/spn #######
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
######End Login with secrete/spn #######

      - name: Apply Dacpac to ACC SQL Database
        uses: azure/sql-actions@v2
        with:
          connection-string: 'Server=lksql.database.windows.net; User ID=sqladmin; Password=Azure$2023;Initial Catalog=test'
          path: ${{github.workspace}}/${{github.projectName}}/${{github.projectName}}.dacpac
          action: 'publish'


    



################## End: Deploy to ACC #####################
